Repository qdai123/moveopluscustom, pull requests merged in 2024-09, with the labels that each got.

#151 [HOTFIX] mv_sale: Cập nhật thêm điều kiện tính số liệu cho Đơn hàng Khuyến Mãi của Chiết khấu Sản Lượng
  mv_sale/models/mv_compute_discount_line.py
Labels: bugs - issues feedback, enhancement

#150 [UP] CẬP NHẬT, BỔ SUNG TÍNH NĂNG "PHIẾU KHẢO SÁT ĐẠI LÝ MO+"
  mv_dms/__manifest__.py
  mv_dms/data/mv_brand_data.xml
  mv_dms/models/__init__.py
  mv_dms/models/mv_brand.py
  mv_dms/models/mv_brand_category.py
  mv_dms/models/mv_brand_proportion.py
  mv_dms/models/mv_partner_survey.py
  mv_dms/models/mv_product_attribute.py
  mv_dms/models/mv_product_product.py
  mv_dms/models/mv_region.py
  mv_dms/models/mv_service_detail.py
  mv_dms/models/mv_shop.py
  mv_dms/models/mv_shop_category.py
  mv_dms/security/ir.model.access.csv
  mv_dms/static/img/placeholder_thumbnail.png
  mv_dms/views/menus.xml
  mv_dms/views/mv_brand_category_views.xml
  mv_dms/views/mv_brand_proportion.xml
  mv_dms/views/mv_brand_views.xml
  mv_dms/views/mv_partner_survey_views.xml
  mv_dms/views/mv_product_attribute_views.xml
  mv_dms/views/mv_product_product_views.xml
  mv_dms/views/mv_service_detail_views.xml
  mv_dms/views/mv_shop_category_views.xml
  mv_dms/views/mv_shop_views.xml
  mv_uom/__init__.py
  mv_uom/__manifest__.py
  mv_uom/data/uom_data.xml
  mv_uom/static/description/icon.png
  mv_uom/static/description/icon.svg
Labels: enhancement

#153 Update mv_partner_survey_views.xml
  mv_dms/views/mv_partner_survey_views.xml
Labels: refactor code

#158 [FIX] mv_dms: Xử lý lỗi không thể xóa Partner Survey
  mv_dms/models/mv_partner_survey.py
Labels: bugs - issues feedback

#163 Mo52: HelpDesk+loyalty: Ghi log khi có chỉnh sửa thông tin trong claim warranty và loyalty program
  mv_helpdesk/models/__init__.py
  mv_helpdesk/models/helpdesk_ticket.py
  mv_helpdesk/models/ir_attachment.py
  mv_sale/models/loyalty_program.py
  mv_sale/views/loyalty_program_views.xml
Labels: bugs - issues feedback, refactor code, conflicts code

#165 Change or to comma in product specification in website
  mv_website_sale/__manifest__.py
  mv_website_sale/views/website_sale_comparison_template.xml
Labels: enhancement

#168 [DEV] mv_sale,mv_dashboard_sale: Dashboard Chart Update 20092024
  mv_dashboard_sale/__manifest__.py
  mv_dashboard_sale/data/default_dashboard_data.xml
  mv_dashboard_sale/data/default_dashboard_item_data.xml
  mv_dashboard_sale/data/default_dashboard_template_data.xml
  mv_dashboard_sale/data/files/BAO-CAO-TONG-HOP.json
  mv_dashboard_sale/data/files/dashboard_sale_bao_cao_tong_hop.json
  mv_sale/report/sales_data_report.py
Labels: enhancement
