Repository qdai123/moveopluscustom, pull requests merged in 2024-08, with the labels that each got.

#97 [DEV+FIX] mv_sale: Discount History of Partner Agency (70% DONE)
  mv_sale/__manifest__.py
  mv_sale/data/ir_cron_data.xml
  mv_sale/models/__init__.py
  mv_sale/models/mv_compute_discount.py
  mv_sale/models/mv_compute_discount_line.py
  mv_sale/models/mv_discount_partner.py
  mv_sale/models/mv_discount_partner_history.py
  mv_sale/models/mv_discount_warranty.py
  mv_sale/models/mv_promote_discount_line.py
  mv_sale/models/res_partner.py
  mv_sale/models/sale_order.py
  mv_sale/models/sale_order_line.py
  mv_sale/report/salesperson_report.py
  mv_sale/security/ir.model.access.csv
  mv_sale/views/mv_compute_discount_line_views.xml
  mv_sale/views/mv_compute_discount_views.xml
  mv_sale/views/mv_discount_partner_history_views.xml
  mv_sale/views/res_partner_views.xml
  mv_sale/wizard/mv_wizard_discount.py
  mv_sale/wizard/mv_wizard_promote_discount_line.py
  mv_sale/wizard/mv_wizard_promote_discount_line_views.xml
  mv_zalo/models/mv_compute_discount.py
  mv_zalo/models/mv_compute_discount_line.py
  mv_zalo/models/mv_compute_warranty_discount_policy.py
Labels: bug, good first issue, Refactor code

#99 [DEV+FIX] mv_sale,mv_website_sale: Cập nhật tính năng theo yêu cầu của Mr.An ngày 05/08/2024
  mv_sale/controllers/portal.py
  mv_sale/models/mv_compute_discount.py
  mv_sale/models/mv_compute_discount_line.py
  mv_sale/models/mv_discount_partner_history.py
  mv_sale/models/mv_discount_warranty.py
  mv_sale/models/res_partner.py
  mv_sale/models/sale_order.py
  mv_sale/views/mv_discount_partner_history_views.xml
  mv_sale/views/sale_portal_templates.xml
  mv_sale/wizard/mv_wizard_discount.py
  mv_website_sale/controllers/main.py
  mv_website_sale/views/portal_templates.xml
Labels: bug, enhancement, Refactor code

#100 [DEV] mv_sale: Thêm trường dữ liệu Max Quantity trên Promote của Sản Phẩm, điều chỉnh lại luồng kiểm tra thêm Max Quantity
  mv_sale/__manifest__.py
  mv_sale/models/__init__.py
  mv_sale/models/loyalty_program.py
  mv_sale/models/loyalty_rule.py
  mv_sale/models/sale_order.py
  mv_sale/views/loyalty_rule_views.xml
  mv_website_sale/views/templates.xml
Labels: bug, enhancement, Refactor code

#101 [DEV] mv_sale,mv_helpdesk: Sửa lỗi tạo Ticket ở màn hình BE, cập nhật tính năng ghi nhận lịch sử từng Số tiền chiết khấu của Đại lý trong phần Chiết Khấu Sản Lượng
  mv_helpdesk/models/helpdesk_ticket.py
  mv_sale/controllers/portal.py
  mv_sale/models/mv_compute_discount.py
  mv_sale/models/mv_compute_discount_line.py
  mv_sale/models/mv_discount_partner_history.py
  mv_sale/security/ir.model.access.csv
  mv_sale/views/mv_compute_discount_views.xml
  mv_sale/views/sale_portal_templates.xml
Labels: bug, enhancement, Refactor code

#103 [DEV] mv_sale: Viết action load dữ liệu Lịch sử chiết khấu của các tháng trước có dữ liệu
  mv_base/models/__init__.py
  mv_base/models/res_users.py
  mv_sale/controllers/portal.py
  mv_sale/models/mv_discount_partner_history.py
  mv_sale/models/res_partner.py
  mv_sale/views/mv_discount_partner_history_views.xml
  mv_sale/views/res_partner_views.xml
  mv_sale/views/sale_portal_templates.xml
Labels: enhancement, Refactor code

#109 [DEV+FIX] mv_helpdesk: Sửa lỗi tạo ticket bị trùng Số Serial Number, điều chỉnh bị thay đổi Ticket Team mặc định ở màn hình Kích Hoạt Bảo Hành
  mv_helpdesk/models/helpdesk_ticket.py
  mv_website_helpdesk/controllers/main.py
  mv_website_helpdesk/data/website_helpdesk_data.xml
  mv_website_helpdesk/static/src/js/helpdesk_warranty_activation_form.js
  mv_website_helpdesk/views/helpdesk_templates.xml
Labels: bug, enhancement, Refactor code

#114 [DEV+FIX] mv_sale,mv_website_sale: Điều chỉnh tính năng ghi nhận lịch sử ví của Đại lý MO+, lọc bỏ thông tin các loại sản phẩm Dịch Vụ ở màn hình Cart và Checkout của Portal
  mv_sale/models/mv_compute_discount.py
  mv_sale/models/mv_compute_discount_line.py
  mv_sale/models/mv_discount_warranty.py
  mv_sale/models/res_partner.py
  mv_sale/models/sale_order.py
  mv_sale/views/mv_compute_discount_views.xml
  mv_sale/views/mv_compute_warranty_discount_policy_views.xml
  mv_sale/views/res_partner_views.xml
  mv_website_sale/models/sale_order.py
  mv_website_sale/views/templates.xml
Labels: bugs - issues feedback, enhancement, refactor code

#118 [NEW] Tạo mới model [mv.partner.area] - Cấu hình Khu vực Đại lý
  mv_partner_survey/__manifest__.py
  mv_partner_survey/models/__init__.py
  mv_partner_survey/models/mv_partner_area.py
  mv_partner_survey/security/ir.model.access.csv
  mv_partner_survey/views/mv_partner_area_views.xml
  mv_partner_survey/views/mv_partner_views.xml
  mv_partner_survey/views/partner_area_menu.xml
Labels: enhancement

#120 [NEW] Tạo mới model [mv.brand] - Cấu hình Hãng lốp / Thương hiệu
  mv_partner_survey/__manifest__.py
  mv_partner_survey/models/__init__.py
  mv_partner_survey/models/mv_brand.py
  mv_partner_survey/security/ir.model.access.csv
  mv_partner_survey/views/mv_brand_views.xml
  mv_partner_survey/views/partner_area_menu.xml
Labels: enhancement

#121 [DEV] mv_partner_survey: Bổ sung Basic Fields, Relational Fields, Auto Sequence for Survey Name
  mv_partner_survey/__manifest__.py
  mv_partner_survey/data/mail_template_data.xml
  mv_partner_survey/data/partner_survey_data.xml
  mv_partner_survey/data/service_cron.xml
  mv_partner_survey/models/__init__.py
  mv_partner_survey/models/mv_partner_survey.py
  mv_partner_survey/models/res_partner.py
  mv_partner_survey/models/res_users.py
Labels: enhancement

#122 [NEW] Tạo mới model [mv.shop] - Thông tin Cửa hàng cho Đại lý
  mv_partner_survey/__manifest__.py
  mv_partner_survey/security/ir.model.access.csv
  mv_partner_survey/security/partner_survey_security.xml
  mv_partner_survey/views/mv_shop_views.xml
Labels: bugs - issues feedback, enhancement

#134 [NEW] Tạo mới model [mv.brand.proportion] - Tỷ trọng theo mỗi Hãng lốp / Thương hiệu
  mv_partner_survey/__manifest__.py
  mv_partner_survey/models/__init__.py
  mv_partner_survey/models/mv_brand_proportion.py
  mv_partner_survey/security/ir.model.access.csv
  mv_partner_survey/security/security.xml
  mv_partner_survey/views/mv_brand_proportion.xml
  mv_partner_survey/views/partner_area_menu.xml
Labels: enhancement

#149 [DEV] mv_sale: Bổ sung thông tin Đơn Giá Chiết Khấu trên Báo cáo bán hàng cho Saler
  mv_sale/report/salesperson_report.py
  mv_sale/report/salesperson_report_views.xml
Labels: enhancement
