Repository qdai123/moveopluscustom, pull requests merged in 2024-10, with the labels that each got.

#176 Fix SQL query in helpdesk
  mv_helpdesk/report/helpdesk_stock_move_line_report.py
Labels: bugs - issues feedback

#173 [DEV] mv_sale: Điều chỉnh lại luồng tính Chiết Khấu Sản Lượng cho Đại lý theo CT mới cho TH 2 tháng và TH Quý
  mv_helpdesk/report/helpdesk_stock_move_line_report_views.xml
  mv_sale/models/mv_compute_discount.py
  mv_sale/models/mv_compute_discount_line.py
  mv_sale/views/mv_compute_discount_line_views.xml
  mv_sale/views/mv_compute_discount_views.xml
Labels: documentation, enhancement, refactor code, conflicts code

#184 Update mv_brand_proportion.py
  mv_dms/models/mv_brand_proportion.py
Labels: bugs - issues feedback

#185 Update mv_discount_warranty.py
  mv_sale/models/mv_discount_warranty.py
Labels: bugs - issues feedback

#186 Update mv_discount_warranty.py
  mv_sale/models/mv_discount_warranty.py
Labels: bugs - issues feedback, enhancement
